version: '3.8'
services:

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 3000:3000
    environment:
      - GRPC_PORT=50051
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
    depends_on:
      - redis